# Generated by Django 5.0.6 on 2024-05-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user_role',
            field=models.IntegerField(null=True),
        ),
    ]
