# Generated by Django 5.0.6 on 2024-05-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_user_role_userdetails_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='profile_pic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
