# Generated by Django 5.0.6 on 2024-05-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userdetails_joining_data_userdetails_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='joining_data',
            new_name='joining_date',
        ),
    ]
