# Generated by Django 5.0.6 on 2024-06-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userdetails_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='active',
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
