# Generated by Django 5.0.6 on 2024-06-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userdetails_active_user_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'organization',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='userdetails',
            name='org_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization1', to='user.organization'),
        ),
    ]
