# Generated by Django 5.0.6 on 2024-06-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_organization_userdetails_org_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='org_id',
            new_name='org',
        ),
    ]
