# Generated by Django 5.0.6 on 2024-06-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_org_id_userdetails_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
