# Generated by Django 5.0.6 on 2024-07-31 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_organization_org_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('doc_loaction', models.CharField(max_length=512, null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='user.user')),
            ],
        ),
    ]
