# Generated by Django 5.0.6 on 2024-05-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainLookup',
            fields=[
                ('domain_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('domain_value', models.CharField(max_length=150)),
                ('domain_code', models.IntegerField()),
                ('domain_type', models.CharField(max_length=150)),
                ('domain_text', models.CharField(blank=True, max_length=150, null=True)),
                ('domain_data_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'domain_lookup',
                'managed': True,
            },
        ),
    ]
